#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#define ITEM_NONE 0

// Balls
#define FIRST_BALL_ID      (ITEM_NONE + 1)
#define ITEM_MASTER_BALL   (FIRST_BALL_ID + 0)
#define ITEM_ULTRA_BALL    (FIRST_BALL_ID + 1)
#define ITEM_GREAT_BALL    (FIRST_BALL_ID + 2)
#define ITEM_POKE_BALL     (FIRST_BALL_ID + 3)
#define ITEM_SAFARI_BALL   (FIRST_BALL_ID + 4)
#define ITEM_NET_BALL      (FIRST_BALL_ID + 5)
#define ITEM_DIVE_BALL     (FIRST_BALL_ID + 6)
#define ITEM_NEST_BALL     (FIRST_BALL_ID + 7)
#define ITEM_REPEAT_BALL   (FIRST_BALL_ID + 8)
#define ITEM_TIMER_BALL    (FIRST_BALL_ID + 9)
#define ITEM_LUXURY_BALL   (FIRST_BALL_ID + 10)
#define ITEM_PREMIER_BALL  (FIRST_BALL_ID + 11)
#define LAST_BALL_ID       (ITEM_PREMIER_BALL)

// Note: If moving ball IDs around, updating FIRST_BALL/LAST_BALL is not sufficient
//       Several places expect the ball IDs to be first and contiguous (e.g. gBattlescriptsForBallThrow and MON_DATA_POKEBALL)
//       If adding new balls, it's easiest to insert them after the last ball and increment the below IDs (and removing ITEM_035 for example)
#define FIRST_BALL FIRST_BALL_ID
#define LAST_BALL  LAST_BALL_ID

// Pokémon Items
#define FIRST_CONSUMABLE_ID (LAST_BALL_ID + 1)
#define ITEM_POTION         (FIRST_CONSUMABLE_ID + 0)
#define ITEM_ANTIDOTE       (FIRST_CONSUMABLE_ID + 1)
#define ITEM_BURN_HEAL      (FIRST_CONSUMABLE_ID + 2)
#define ITEM_ICE_HEAL       (FIRST_CONSUMABLE_ID + 3)
#define ITEM_AWAKENING      (FIRST_CONSUMABLE_ID + 4)
#define ITEM_PARALYZE_HEAL  (FIRST_CONSUMABLE_ID + 5)
#define ITEM_FULL_RESTORE   (FIRST_CONSUMABLE_ID + 6)
#define ITEM_MAX_POTION     (FIRST_CONSUMABLE_ID + 7)
#define ITEM_HYPER_POTION   (FIRST_CONSUMABLE_ID + 8)
#define ITEM_SUPER_POTION   (FIRST_CONSUMABLE_ID + 9)
#define ITEM_FULL_HEAL      (FIRST_CONSUMABLE_ID + 10)
#define ITEM_REVIVE         (FIRST_CONSUMABLE_ID + 11)
#define ITEM_MAX_REVIVE     (FIRST_CONSUMABLE_ID + 12)
#define ITEM_FRESH_WATER    (FIRST_CONSUMABLE_ID + 13)
#define ITEM_SODA_POP       (FIRST_CONSUMABLE_ID + 14)
#define ITEM_LEMONADE       (FIRST_CONSUMABLE_ID + 15)
#define ITEM_MOOMOO_MILK    (FIRST_CONSUMABLE_ID + 16)
#define ITEM_ENERGY_POWDER  (FIRST_CONSUMABLE_ID + 17)
#define ITEM_ENERGY_ROOT    (FIRST_CONSUMABLE_ID + 18)
#define ITEM_HEAL_POWDER    (FIRST_CONSUMABLE_ID + 19)
#define ITEM_REVIVAL_HERB   (FIRST_CONSUMABLE_ID + 20)
#define ITEM_ETHER          (FIRST_CONSUMABLE_ID + 21)
#define ITEM_MAX_ETHER      (FIRST_CONSUMABLE_ID + 22)
#define ITEM_ELIXIR         (FIRST_CONSUMABLE_ID + 23)
#define ITEM_MAX_ELIXIR     (FIRST_CONSUMABLE_ID + 24)
#define ITEM_LAVA_COOKIE    (FIRST_CONSUMABLE_ID + 25)
#define ITEM_BLUE_FLUTE     (FIRST_CONSUMABLE_ID + 26)
#define ITEM_YELLOW_FLUTE   (FIRST_CONSUMABLE_ID + 27)
#define ITEM_RED_FLUTE      (FIRST_CONSUMABLE_ID + 28)
#define ITEM_BLACK_FLUTE    (FIRST_CONSUMABLE_ID + 29)
#define ITEM_WHITE_FLUTE    (FIRST_CONSUMABLE_ID + 30)
#define ITEM_BERRY_JUICE    (FIRST_CONSUMABLE_ID + 31)
#define ITEM_SACRED_ASH     (FIRST_CONSUMABLE_ID + 32)
#define ITEM_SHOAL_SALT     (FIRST_CONSUMABLE_ID + 33)
#define ITEM_SHOAL_SHELL    (FIRST_CONSUMABLE_ID + 34)
#define ITEM_RED_SHARD      (FIRST_CONSUMABLE_ID + 35)
#define ITEM_BLUE_SHARD     (FIRST_CONSUMABLE_ID + 36)
#define ITEM_YELLOW_SHARD   (FIRST_CONSUMABLE_ID + 37)
#define ITEM_GREEN_SHARD    (FIRST_CONSUMABLE_ID + 38)
// Vitamins
#define ITEM_HP_UP          (FIRST_CONSUMABLE_ID + 39)
#define ITEM_PROTEIN        (FIRST_CONSUMABLE_ID + 40)
#define ITEM_IRON           (FIRST_CONSUMABLE_ID + 41)
#define ITEM_CARBOS         (FIRST_CONSUMABLE_ID + 42)
#define ITEM_CALCIUM        (FIRST_CONSUMABLE_ID + 43)
#define ITEM_RARE_CANDY     (FIRST_CONSUMABLE_ID + 44)
#define ITEM_PP_UP          (FIRST_CONSUMABLE_ID + 45)
#define ITEM_ZINC           (FIRST_CONSUMABLE_ID + 46)
#define ITEM_PP_MAX         (FIRST_CONSUMABLE_ID + 47)
// In-battle items
#define ITEM_GUARD_SPEC     (FIRST_CONSUMABLE_ID + 48)
#define ITEM_DIRE_HIT       (FIRST_CONSUMABLE_ID + 49)
#define ITEM_X_ATTACK       (FIRST_CONSUMABLE_ID + 50)
#define ITEM_X_DEFEND       (FIRST_CONSUMABLE_ID + 51)
#define ITEM_X_SPEED        (FIRST_CONSUMABLE_ID + 52)
#define ITEM_X_ACCURACY     (FIRST_CONSUMABLE_ID + 53)
#define ITEM_X_SPECIAL      (FIRST_CONSUMABLE_ID + 54)
// Repelling items
#define ITEM_POKE_DOLL      (FIRST_CONSUMABLE_ID + 55)
#define ITEM_FLUFFY_TAIL    (FIRST_CONSUMABLE_ID + 56)
#define ITEM_SUPER_REPEL    (FIRST_CONSUMABLE_ID + 57)
#define ITEM_MAX_REPEL      (FIRST_CONSUMABLE_ID + 58)
#define ITEM_ESCAPE_ROPE    (FIRST_CONSUMABLE_ID + 59)
#define ITEM_REPEL          (FIRST_CONSUMABLE_ID + 60)
// Evolution stones
#define ITEM_SUN_STONE      (FIRST_CONSUMABLE_ID + 61)
#define ITEM_MOON_STONE     (FIRST_CONSUMABLE_ID + 62)
#define ITEM_FIRE_STONE     (FIRST_CONSUMABLE_ID + 63)
#define ITEM_THUNDER_STONE  (FIRST_CONSUMABLE_ID + 64)
#define ITEM_WATER_STONE    (FIRST_CONSUMABLE_ID + 65)
#define ITEM_LEAF_STONE     (FIRST_CONSUMABLE_ID + 66)
#define ITEM_LINK_STONE     (FIRST_CONSUMABLE_ID + 67)

#define FIRST_EVO_STONE ITEM_SUN_STONE
#define LAST_EVO_STONE ITEM_LINK_STONE
#define LAST_CONSUMABLE_ID  (ITEM_LINK_STONE)

// Collectables
#define FIRST_COLLECTABLE_ID (LAST_CONSUMABLE_ID + 1)
#define ITEM_TINY_MUSHROOM   (FIRST_COLLECTABLE_ID + 0)
#define ITEM_BIG_MUSHROOM    (FIRST_COLLECTABLE_ID + 1)
#define ITEM_PEARL           (FIRST_COLLECTABLE_ID + 2)
#define ITEM_BIG_PEARL       (FIRST_COLLECTABLE_ID + 3)
#define ITEM_STARDUST        (FIRST_COLLECTABLE_ID + 4)
#define ITEM_STAR_PIECE      (FIRST_COLLECTABLE_ID + 5)
#define ITEM_NUGGET          (FIRST_COLLECTABLE_ID + 6)
#define ITEM_HEART_SCALE     (FIRST_COLLECTABLE_ID + 7)
#define LAST_COLLECTABLE_ID  (ITEM_HEART_SCALE)

// Mails
#define FIRST_MAIL_ID     (LAST_COLLECTABLE_ID + 1)
#define ITEM_ORANGE_MAIL  (FIRST_MAIL_ID + 0)
#define ITEM_HARBOR_MAIL  (FIRST_MAIL_ID + 1)
#define ITEM_GLITTER_MAIL (FIRST_MAIL_ID + 2)
#define ITEM_MECH_MAIL    (FIRST_MAIL_ID + 3)
#define ITEM_WOOD_MAIL    (FIRST_MAIL_ID + 4)
#define ITEM_WAVE_MAIL    (FIRST_MAIL_ID + 5)
#define ITEM_BEAD_MAIL    (FIRST_MAIL_ID + 6)
#define ITEM_SHADOW_MAIL  (FIRST_MAIL_ID + 7)
#define ITEM_TROPIC_MAIL  (FIRST_MAIL_ID + 8)
#define ITEM_DREAM_MAIL   (FIRST_MAIL_ID + 9)
#define ITEM_FAB_MAIL     (FIRST_MAIL_ID + 10)
#define ITEM_RETRO_MAIL   (FIRST_MAIL_ID + 11)

#define FIRST_MAIL_INDEX  (ITEM_ORANGE_MAIL)
#define LAST_MAIL_ID      (ITEM_RETRO_MAIL)

// Berries
#define FIRST_BERRY_ID    (LAST_MAIL_ID + 1)
#define ITEM_CHERI_BERRY  (FIRST_BERRY_ID + 0)
#define ITEM_CHESTO_BERRY (FIRST_BERRY_ID + 1)
#define ITEM_PECHA_BERRY  (FIRST_BERRY_ID + 2)
#define ITEM_RAWST_BERRY  (FIRST_BERRY_ID + 3)
#define ITEM_ASPEAR_BERRY (FIRST_BERRY_ID + 4)
#define ITEM_LEPPA_BERRY  (FIRST_BERRY_ID + 5)
#define ITEM_ORAN_BERRY   (FIRST_BERRY_ID + 6)
#define ITEM_PERSIM_BERRY (FIRST_BERRY_ID + 7)
#define ITEM_LUM_BERRY    (FIRST_BERRY_ID + 8)
#define ITEM_SITRUS_BERRY (FIRST_BERRY_ID + 9)
#define ITEM_FIGY_BERRY   (FIRST_BERRY_ID + 10)
#define ITEM_WIKI_BERRY   (FIRST_BERRY_ID + 11)
#define ITEM_MAGO_BERRY   (FIRST_BERRY_ID + 12)
#define ITEM_AGUAV_BERRY  (FIRST_BERRY_ID + 13)
#define ITEM_IAPAPA_BERRY (FIRST_BERRY_ID + 14)
#define ITEM_RAZZ_BERRY   (FIRST_BERRY_ID + 15)
#define ITEM_BLUK_BERRY   (FIRST_BERRY_ID + 16)
#define ITEM_NANAB_BERRY  (FIRST_BERRY_ID + 17)
#define ITEM_WEPEAR_BERRY (FIRST_BERRY_ID + 18)
#define ITEM_PINAP_BERRY  (FIRST_BERRY_ID + 19)
#define ITEM_POMEG_BERRY  (FIRST_BERRY_ID + 20)
#define ITEM_KELPSY_BERRY (FIRST_BERRY_ID + 21)
#define ITEM_QUALOT_BERRY (FIRST_BERRY_ID + 22)
#define ITEM_HONDEW_BERRY (FIRST_BERRY_ID + 23)
#define ITEM_GREPA_BERRY  (FIRST_BERRY_ID + 24)
#define ITEM_TAMATO_BERRY (FIRST_BERRY_ID + 25)
#define ITEM_CORNN_BERRY  (FIRST_BERRY_ID + 26)
#define ITEM_MAGOST_BERRY (FIRST_BERRY_ID + 27)
#define ITEM_RABUTA_BERRY (FIRST_BERRY_ID + 28)
#define ITEM_NOMEL_BERRY  (FIRST_BERRY_ID + 29)
#define ITEM_SPELON_BERRY (FIRST_BERRY_ID + 30)
#define ITEM_PAMTRE_BERRY (FIRST_BERRY_ID + 31)
#define ITEM_WATMEL_BERRY (FIRST_BERRY_ID + 32)
#define ITEM_DURIN_BERRY  (FIRST_BERRY_ID + 33)
#define ITEM_BELUE_BERRY  (FIRST_BERRY_ID + 34)
#define ITEM_LIECHI_BERRY (FIRST_BERRY_ID + 35)
#define ITEM_GANLON_BERRY (FIRST_BERRY_ID + 36)
#define ITEM_SALAC_BERRY  (FIRST_BERRY_ID + 37)
#define ITEM_PETAYA_BERRY (FIRST_BERRY_ID + 38)
#define ITEM_APICOT_BERRY (FIRST_BERRY_ID + 39)
#define ITEM_LANSAT_BERRY (FIRST_BERRY_ID + 40)
#define ITEM_STARF_BERRY  (FIRST_BERRY_ID + 41)
#define ITEM_ENIGMA_BERRY (FIRST_BERRY_ID + 42)
#define LAST_BERRY_ID     (ITEM_ENIGMA_BERRY)

#define FIRST_BERRY_INDEX FIRST_BERRY_ID
#define LAST_BERRY_INDEX  LAST_BERRY_ID
#define MAX_BERRY_INDEX LAST_BERRY_ID

// Battle Held items
#define FIRST_HELD_ID       (LAST_BERRY_ID + 1)
#define ITEM_BRIGHT_POWDER  (FIRST_HELD_ID + 0)
#define ITEM_WHITE_HERB     (FIRST_HELD_ID + 1)
#define ITEM_MACHO_BRACE    (FIRST_HELD_ID + 2)
#define ITEM_EXP_SHARE      (FIRST_HELD_ID + 3)
#define ITEM_QUICK_CLAW     (FIRST_HELD_ID + 4)
#define ITEM_SOOTHE_BELL    (FIRST_HELD_ID + 5)
#define ITEM_MENTAL_HERB    (FIRST_HELD_ID + 6)
#define ITEM_CHOICE_BAND    (FIRST_HELD_ID + 7)
#define ITEM_KINGS_ROCK     (FIRST_HELD_ID + 8)
#define ITEM_SILVER_POWDER  (FIRST_HELD_ID + 9)
#define ITEM_AMULET_COIN    (FIRST_HELD_ID + 10)
#define ITEM_CLEANSE_TAG    (FIRST_HELD_ID + 11)
#define ITEM_SOUL_DEW       (FIRST_HELD_ID + 12)
#define ITEM_DEEP_SEA_TOOTH (FIRST_HELD_ID + 13)
#define ITEM_DEEP_SEA_SCALE (FIRST_HELD_ID + 14)
#define ITEM_SMOKE_BALL     (FIRST_HELD_ID + 15)
#define ITEM_EVERSTONE      (FIRST_HELD_ID + 16)
#define ITEM_FOCUS_BAND     (FIRST_HELD_ID + 17)
#define ITEM_LUCKY_EGG      (FIRST_HELD_ID + 18)
#define ITEM_SCOPE_LENS     (FIRST_HELD_ID + 19)
#define ITEM_METAL_COAT     (FIRST_HELD_ID + 20)
#define ITEM_LEFTOVERS      (FIRST_HELD_ID + 21)
#define ITEM_DRAGON_SCALE   (FIRST_HELD_ID + 22)
#define ITEM_LIGHT_BALL     (FIRST_HELD_ID + 23)
#define ITEM_SOFT_SAND      (FIRST_HELD_ID + 24)
#define ITEM_HARD_STONE     (FIRST_HELD_ID + 25)
#define ITEM_MIRACLE_SEED   (FIRST_HELD_ID + 26)
#define ITEM_BLACK_GLASSES  (FIRST_HELD_ID + 27)
#define ITEM_BLACK_BELT     (FIRST_HELD_ID + 28)
#define ITEM_MAGNET         (FIRST_HELD_ID + 29)
#define ITEM_MYSTIC_WATER   (FIRST_HELD_ID + 30)
#define ITEM_SHARP_BEAK     (FIRST_HELD_ID + 31)
#define ITEM_POISON_BARB    (FIRST_HELD_ID + 32)
#define ITEM_NEVER_MELT_ICE (FIRST_HELD_ID + 33)
#define ITEM_SPELL_TAG      (FIRST_HELD_ID + 34)
#define ITEM_TWISTED_SPOON  (FIRST_HELD_ID + 35)
#define ITEM_CHARCOAL       (FIRST_HELD_ID + 36)
#define ITEM_DRAGON_FANG    (FIRST_HELD_ID + 37)
#define ITEM_SILK_SCARF     (FIRST_HELD_ID + 38)
#define ITEM_UP_GRADE       (FIRST_HELD_ID + 39)
#define ITEM_SHELL_BELL     (FIRST_HELD_ID + 40)
#define ITEM_SEA_INCENSE    (FIRST_HELD_ID + 41)
#define ITEM_LAX_INCENSE    (FIRST_HELD_ID + 42)
#define ITEM_LUCKY_PUNCH    (FIRST_HELD_ID + 43)
#define ITEM_METAL_POWDER   (FIRST_HELD_ID + 44)
#define ITEM_THICK_CLUB     (FIRST_HELD_ID + 45)
#define ITEM_STICK          (FIRST_HELD_ID + 46)
#define ITEM_RED_SCARF      (FIRST_HELD_ID + 47)
#define ITEM_BLUE_SCARF     (FIRST_HELD_ID + 48)
#define ITEM_PINK_SCARF     (FIRST_HELD_ID + 49)
#define ITEM_GREEN_SCARF    (FIRST_HELD_ID + 50)
#define ITEM_YELLOW_SCARF   (FIRST_HELD_ID + 51)
#define LAST_HELD_ID        (ITEM_YELLOW_SCARF)

// Key Items
#define FIRST_KEY_ID        (LAST_HELD_ID + 1)
#define ITEM_MACH_BIKE      (FIRST_KEY_ID + 0)
#define ITEM_COIN_CASE      (FIRST_KEY_ID + 1)
#define ITEM_ITEMFINDER     (FIRST_KEY_ID + 2)
#define ITEM_OLD_ROD        (FIRST_KEY_ID + 3)
#define ITEM_GOOD_ROD       (FIRST_KEY_ID + 4)
#define ITEM_SUPER_ROD      (FIRST_KEY_ID + 5)
#define ITEM_SS_TICKET      (FIRST_KEY_ID + 6)
#define ITEM_CONTEST_PASS   (FIRST_KEY_ID + 7)
#define ITEM_WAILMER_PAIL   (FIRST_KEY_ID + 8)
#define ITEM_DEVON_GOODS    (FIRST_KEY_ID + 9)
#define ITEM_SOOT_SACK      (FIRST_KEY_ID + 10)
#define ITEM_BASEMENT_KEY   (FIRST_KEY_ID + 11)
#define ITEM_ACRO_BIKE      (FIRST_KEY_ID + 12)
#define ITEM_POKEBLOCK_CASE (FIRST_KEY_ID + 13)
#define ITEM_LETTER         (FIRST_KEY_ID + 14)
#define ITEM_EON_TICKET     (FIRST_KEY_ID + 15)
#define ITEM_RED_ORB        (FIRST_KEY_ID + 16)
#define ITEM_BLUE_ORB       (FIRST_KEY_ID + 17)
#define ITEM_SCANNER        (FIRST_KEY_ID + 18)
#define ITEM_GO_GOGGLES     (FIRST_KEY_ID + 19)
#define ITEM_METEORITE      (FIRST_KEY_ID + 20)
#define ITEM_ROOM_1_KEY     (FIRST_KEY_ID + 21)
#define ITEM_ROOM_2_KEY     (FIRST_KEY_ID + 22)
#define ITEM_ROOM_4_KEY     (FIRST_KEY_ID + 23)
#define ITEM_ROOM_6_KEY     (FIRST_KEY_ID + 24)
#define ITEM_STORAGE_KEY    (FIRST_KEY_ID + 25)
#define ITEM_ROOT_FOSSIL    (FIRST_KEY_ID + 26)
#define ITEM_CLAW_FOSSIL    (FIRST_KEY_ID + 27)
#define ITEM_DEVON_SCOPE    (FIRST_KEY_ID + 28)
#define ITEM_DEBUGGER       (FIRST_KEY_ID + 29)
#define LAST_KEY_ID         (ITEM_DEBUGGER)

// TMs/HMs
#define FIRST_TMHM_ID (LAST_KEY_ID + 1)
#define ITEM_TM01     (FIRST_TMHM_ID + 0)
#define ITEM_TM02     (FIRST_TMHM_ID + 1)
#define ITEM_TM03     (FIRST_TMHM_ID + 2)
#define ITEM_TM04     (FIRST_TMHM_ID + 3)
#define ITEM_TM05     (FIRST_TMHM_ID + 4)
#define ITEM_TM06     (FIRST_TMHM_ID + 5)
#define ITEM_TM07     (FIRST_TMHM_ID + 6)
#define ITEM_TM08     (FIRST_TMHM_ID + 7)
#define ITEM_TM09     (FIRST_TMHM_ID + 8)
#define ITEM_TM10     (FIRST_TMHM_ID + 9)
#define ITEM_TM11     (FIRST_TMHM_ID + 10)
#define ITEM_TM12     (FIRST_TMHM_ID + 11)
#define ITEM_TM13     (FIRST_TMHM_ID + 12)
#define ITEM_TM14     (FIRST_TMHM_ID + 13)
#define ITEM_TM15     (FIRST_TMHM_ID + 14)
#define ITEM_TM16     (FIRST_TMHM_ID + 15)
#define ITEM_TM17     (FIRST_TMHM_ID + 16)
#define ITEM_TM18     (FIRST_TMHM_ID + 17)
#define ITEM_TM19     (FIRST_TMHM_ID + 18)
#define ITEM_TM20     (FIRST_TMHM_ID + 19)
#define ITEM_TM21     (FIRST_TMHM_ID + 20)
#define ITEM_TM22     (FIRST_TMHM_ID + 21)
#define ITEM_TM23     (FIRST_TMHM_ID + 22)
#define ITEM_TM24     (FIRST_TMHM_ID + 23)
#define ITEM_TM25     (FIRST_TMHM_ID + 24)
#define ITEM_TM26     (FIRST_TMHM_ID + 25)
#define ITEM_TM27     (FIRST_TMHM_ID + 26)
#define ITEM_TM28     (FIRST_TMHM_ID + 27)
#define ITEM_TM29     (FIRST_TMHM_ID + 28)
#define ITEM_TM30     (FIRST_TMHM_ID + 29)
#define ITEM_TM31     (FIRST_TMHM_ID + 30)
#define ITEM_TM32     (FIRST_TMHM_ID + 31)
#define ITEM_TM33     (FIRST_TMHM_ID + 32)
#define ITEM_TM34     (FIRST_TMHM_ID + 33)
#define ITEM_TM35     (FIRST_TMHM_ID + 34)
#define ITEM_TM36     (FIRST_TMHM_ID + 35)
#define ITEM_TM37     (FIRST_TMHM_ID + 36)
#define ITEM_TM38     (FIRST_TMHM_ID + 37)
#define ITEM_TM39     (FIRST_TMHM_ID + 38)
#define ITEM_TM40     (FIRST_TMHM_ID + 39)
#define ITEM_TM41     (FIRST_TMHM_ID + 50)
#define ITEM_TM42     (FIRST_TMHM_ID + 51)
#define ITEM_TM43     (FIRST_TMHM_ID + 52)
#define ITEM_TM44     (FIRST_TMHM_ID + 53)
#define ITEM_TM45     (FIRST_TMHM_ID + 54)
#define ITEM_TM46     (FIRST_TMHM_ID + 55)
#define ITEM_TM47     (FIRST_TMHM_ID + 56)
#define ITEM_TM48     (FIRST_TMHM_ID + 57)
#define ITEM_TM49     (FIRST_TMHM_ID + 58)
#define ITEM_TM50     (FIRST_TMHM_ID + 59)
#define ITEM_HM01     (FIRST_TMHM_ID + 60)
#define ITEM_HM02     (FIRST_TMHM_ID + 61)
#define ITEM_HM03     (FIRST_TMHM_ID + 62)
#define ITEM_HM04     (FIRST_TMHM_ID + 63)
#define ITEM_HM05     (FIRST_TMHM_ID + 64)
#define ITEM_HM06     (FIRST_TMHM_ID + 65)
#define ITEM_HM07     (FIRST_TMHM_ID + 66)
#define ITEM_HM08     (FIRST_TMHM_ID + 67)
#define LAST_TMHM_ID  (ITEM_HM08)

// FireRed/LeafGreen
#define FIRST_FRLG_ID      (LAST_TMHM_ID + 1)
#define ITEM_OAKS_PARCEL   (FIRST_FRLG_ID + 0)
#define ITEM_POKE_FLUTE    (FIRST_FRLG_ID + 1)
#define ITEM_SECRET_KEY    (FIRST_FRLG_ID + 2)
#define ITEM_BIKE_VOUCHER  (FIRST_FRLG_ID + 3)
#define ITEM_GOLD_TEETH    (FIRST_FRLG_ID + 4)
#define ITEM_OLD_AMBER     (FIRST_FRLG_ID + 5)
#define ITEM_CARD_KEY      (FIRST_FRLG_ID + 6)
#define ITEM_LIFT_KEY      (FIRST_FRLG_ID + 7)
#define ITEM_HELIX_FOSSIL  (FIRST_FRLG_ID + 8)
#define ITEM_DOME_FOSSIL   (FIRST_FRLG_ID + 9)
#define ITEM_SILPH_SCOPE   (FIRST_FRLG_ID + 10)
#define ITEM_BICYCLE       (FIRST_FRLG_ID + 11)
#define ITEM_TOWN_MAP      (FIRST_FRLG_ID + 12)
#define ITEM_VS_SEEKER     (FIRST_FRLG_ID + 13)
#define ITEM_FAME_CHECKER  (FIRST_FRLG_ID + 14)
#define ITEM_TM_CASE       (FIRST_FRLG_ID + 15)
#define ITEM_BERRY_POUCH   (FIRST_FRLG_ID + 16)
#define ITEM_TEACHY_TV     (FIRST_FRLG_ID + 17)
#define ITEM_TRI_PASS      (FIRST_FRLG_ID + 18)
#define ITEM_RAINBOW_PASS  (FIRST_FRLG_ID + 19)
#define ITEM_TEA           (FIRST_FRLG_ID + 20)
#define ITEM_MYSTIC_TICKET (FIRST_FRLG_ID + 21)
#define ITEM_AURORA_TICKET (FIRST_FRLG_ID + 22)
#define ITEM_POWDER_JAR    (FIRST_FRLG_ID + 23)
#define ITEM_RUBY          (FIRST_FRLG_ID + 24)
#define ITEM_SAPPHIRE      (FIRST_FRLG_ID + 25)
#define LAST_FRLG_ID       (ITEM_SAPPHIRE)

// Emerald
#define FIRST_EMERALD_ID  (LAST_FRLG_ID + 1)
#define ITEM_MAGMA_EMBLEM (FIRST_EMERALD_ID + 0)
#define ITEM_OLD_SEA_MAP  (FIRST_EMERALD_ID + 1)
#define LAST_EMERALD_ID   (ITEM_OLD_SEA_MAP)

#define ITEMS_COUNT (LAST_EMERALD_ID + 1)

// A special item id associated with "Cancel"/"Exit" etc. in a list of items or decorations
// Its icon is defined at ITEMS_COUNT as the "return to field" arrow
#define ITEM_LIST_END 0xFFFF

// Range of berries given out by various NPCS
#define FIRST_BERRY_MASTER_BERRY      ITEM_POMEG_BERRY
#define LAST_BERRY_MASTER_BERRY       ITEM_NOMEL_BERRY
#define FIRST_BERRY_MASTER_WIFE_BERRY ITEM_CHERI_BERRY
#define LAST_BERRY_MASTER_WIFE_BERRY  ITEM_SITRUS_BERRY
#define FIRST_KIRI_BERRY              ITEM_POMEG_BERRY
#define LAST_KIRI_BERRY               ITEM_NOMEL_BERRY
#define FIRST_ROUTE_114_MAN_BERRY     ITEM_RAZZ_BERRY
#define LAST_ROUTE_114_MAN_BERRY      ITEM_PINAP_BERRY

#define NUM_BERRY_MASTER_BERRIES          (LAST_BERRY_MASTER_BERRY - FIRST_BERRY_MASTER_BERRY + 1)
#define NUM_BERRY_MASTER_BERRIES_SKIPPED  (FIRST_BERRY_MASTER_BERRY - FIRST_BERRY_INDEX)
#define NUM_BERRY_MASTER_WIFE_BERRIES     (LAST_BERRY_MASTER_WIFE_BERRY - FIRST_BERRY_MASTER_WIFE_BERRY + 1)
#define NUM_KIRI_BERRIES                  (LAST_KIRI_BERRY - FIRST_KIRI_BERRY + 1)
#define NUM_KIRI_BERRIES_SKIPPED          (FIRST_KIRI_BERRY - FIRST_BERRY_INDEX)
#define NUM_ROUTE_114_MAN_BERRIES         (LAST_ROUTE_114_MAN_BERRY - FIRST_ROUTE_114_MAN_BERRY + 1)
#define NUM_ROUTE_114_MAN_BERRIES_SKIPPED (FIRST_ROUTE_114_MAN_BERRY - FIRST_BERRY_INDEX)

#define ITEM_TO_BERRY(itemId) (((itemId) - FIRST_BERRY_INDEX) + 1)
#define ITEM_TO_MAIL(itemId) ((itemId) - FIRST_MAIL_INDEX)
#define MAIL_NONE 0xFF

#define NUM_TECHNICAL_MACHINES 50
#define NUM_HIDDEN_MACHINES     8

#define MAX_BAG_ITEM_CAPACITY  99
#define MAX_PC_ITEM_CAPACITY   999
#define MAX_BERRY_CAPACITY     999

#define BAG_ITEM_CAPACITY_DIGITS 2
#define BERRY_CAPACITY_DIGITS 3
#define MAX_ITEM_DIGITS BERRY_CAPACITY_DIGITS

// Secondary IDs for rods
#define OLD_ROD   0
#define GOOD_ROD  1
#define SUPER_ROD 2

// Secondary IDs for bikes
#define MACH_BIKE 0
#define ACRO_BIKE 1

// Item type IDs (used to determine the exit callback)
#define ITEM_USE_MAIL        0
#define ITEM_USE_PARTY_MENU  1
#define ITEM_USE_FIELD       2
#define ITEM_USE_PBLOCK_CASE 3
#define ITEM_USE_BAG_MENU    4 // No exit callback, stays in bag menu

// Item battle usage IDs (only checked to see if nonzero)
#define ITEM_B_USE_MEDICINE 1
#define ITEM_B_USE_OTHER    2

// Check if the item is one that can be used on a Pokémon.
#define ITEM_HAS_EFFECT(item) ((item) >= ITEM_POTION && (item) <= MAX_BERRY_INDEX)

#endif  // GUARD_CONSTANTS_ITEMS_H
