DebugMapMain_MapScripts::
	.byte 0


DebugMapMain_Sign_Littleroot::
# 8 "data/maps/DebugMapMain/scripts.pory"
	msgbox DebugMapMain_Sign_Littleroot_Text_0, MSGBOX_SIGN
	end


DebugMapMain_Sign_RegionMap::
# 14 "data/maps/DebugMapMain/scripts.pory"
	msgbox DebugMapMain_Sign_RegionMap_Text_0, MSGBOX_SIGN
	end


DebugMapMain_Sign_BattleArea::
# 20 "data/maps/DebugMapMain/scripts.pory"
	msgbox DebugMapMain_Sign_BattleArea_Text_0, MSGBOX_SIGN
	end


DebugMapMain_Sign_Scripts::
# 26 "data/maps/DebugMapMain/scripts.pory"
	msgbox DebugMapMain_Sign_Scripts_Text_0, MSGBOX_SIGN
	end


DebugMapMain_Sign_Littleroot_Text_0:
# 8 "data/maps/DebugMapMain/scripts.pory"
	.string "LITTLEROOT TOWN$"

DebugMapMain_Sign_RegionMap_Text_0:
# 14 "data/maps/DebugMapMain/scripts.pory"
	.string "REGION MAP$"

DebugMapMain_Sign_BattleArea_Text_0:
# 20 "data/maps/DebugMapMain/scripts.pory"
	.string "BATTLE AREA$"

DebugMapMain_Sign_Scripts_Text_0:
# 26 "data/maps/DebugMapMain/scripts.pory"
	.string "SCRIPTS$"
