# 1 "data/maps/DebugMapScripts/scripts.pory"

# 2 "data/maps/DebugMapScripts/scripts.pory"
DebugMapScripts_MapScripts::
# 3 "data/maps/DebugMapScripts/scripts.pory"
	.byte 0
# 4 "data/maps/DebugMapScripts/scripts.pory"

# 5 "data/maps/DebugMapScripts/scripts.pory"
DebugMapScripts_Event_TestScript1::
# 6 "data/maps/DebugMapScripts/scripts.pory"
	lockall
# 7 "data/maps/DebugMapScripts/scripts.pory"
	giveitem ITEM_OVAL_CHARM
# 8 "data/maps/DebugMapScripts/scripts.pory"
	releaseall
# 9 "data/maps/DebugMapScripts/scripts.pory"
	end
